# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rccoder
email: rccoder.net@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  在对的时间做正确的事。欢迎你订阅本[博客](https://github.com/rccoder/blog)：Watch + Star
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.rccoder.net" # the base hostname & protocol for your site
weibo_username: rccoder
github_username:  rccoder

# Build settings
markdown: kramdown
kramdown:
    input: GFM

user: rccoder
repo: blog